version: '3.3'

services:
  kenshow8_eth_api:
    image: kenshow8/python3:1.0
    build: .
    container_name: 'kenshow8_eth_api'
    ports:
        - '8080:8080'
    environment:
        WEB3_URL: 'http://$LOCAL_HOST_IP:7545' # ローカルホスト以外にトークンをデプロイしている場合は編集してください。
        CONTRACT_ADDRESS: '${CONTRACT_ADDRESS}'
        OWNER_ADDRESS: '${OWNER_ADDRESS}'
    command: >
        bash -c "
        python /app/eth_erc20_token_python_api/config_make_docker.py &&
        cat /app/eth_erc20_token_python_api/config/setting.ini &&
        python /app/eth_erc20_token_python_api/coin_api.py
        "
